### ISSUE TITLE
Incorrect info about packet count

### ISSUE THREAD

**Issue by DamnFighter** [ebu/pi-list#100]
Hello,

What I have observed, there are some issues with packet count in ebu list. Below you will find some details.

Wireshark and [smpte2110-analyzer - script](https://github.com/ebu/smpte2110-analyzer) returns the same count of packets.

**Pcap**: [PCAP FILE](https://github.com/ebu/pi-list/blob/master/sample_data/pcap/st2110/2110-20/2110-20_720p50.pcap)

**Packets count:**

- Wireshark: 

![image](https://user-images.githubusercontent.com/26457336/92119996-ce7a1100-edf8-11ea-92df-14a8da670c37.png)

- [smpte2110-analyzer - script](https://github.com/ebu/smpte2110-analyzer)

![image](https://user-images.githubusercontent.com/26457336/92120517-71cb2600-edf9-11ea-8371-b098571ed073.png)

- Ebu LIST (latest version)
![image](https://user-images.githubusercontent.com/26457336/92120590-8c9d9a80-edf9-11ea-869c-435483737ea5.png)

**I also observe differences for VRX value:**

- [smpte2110-analyzer - script](https://github.com/ebu/smpte2110-analyzer)

![image](https://user-images.githubusercontent.com/26457336/92120899-e7cf8d00-edf9-11ea-8983-f7d9f4d2a8d0.png)

- Ebu LIST (latest version)

![image](https://user-images.githubusercontent.com/26457336/92120999-0df52d00-edfa-11ea-9c20-f97c673c3ec9.png)

Could you check, is it ok or not?

Best regards,
DF

**Comment by pedro-alves-ferreira** [comment]
Hello,

Many thanks for pointing this out. Coincidentally, we have fixed this problem earlier today. We will push the changes either today or tomorrow.

Regards,

Pedro

**Comment by pedro-alves-ferreira** [comment]
Closed with v1.16.3
