### ISSUE TITLE
Latest LIST won't start as Docker container if host has IPv6 disabled

### ISSUE THREAD

**Issue by firthmj** [ebu/pi-list#104]
The latest version of LIST won't start properly by default on a host that has IPv6 disabled.

I downloaded the latest "docker-compose.yml", updated it as before with the port and EBU_LIST_WEB_APP_DOMAIN variable setting, and ran "docker-compose up".

All the containers appeared to start, but I couldn't connect to the port number I had specified.

Then, scrolling up through the logs, I saw "listserver_1  | Starting nginx: nginx failed!"

I connected to the container and tried a few things to debug the nginx start up, and eventually got "nginx -t" to say:

root@9191228c27d0:/app# nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)
nginx: configuration file /etc/nginx/nginx.conf test failed

I commented out the IPv6 address lines in /etc/nginx/nginx.conf, and then things started and worked when I stopped and restarted the "docker-compose". One thing I'm not quite clear on is how persistent these changes will be, generally I'd expect Docker to throw away all changes between runs of a container, but that doesn't seem to have happened here.

**Comment by pedro-alves-ferreira** [comment]
Hi Michael,

Thanks for reporting this. We will look into it and maybe just disable IPv6.

Regards,

Pedro

**Comment by pedro-alves-ferreira** [comment]
Closed in release 1.17
