### ISSUE TITLE
Cannot analyse Stream (created \w gstreamer 1.0)

### ISSUE THREAD

**Issue by dani-987** [ebu/pi-list#11]
Hey,

now I'm back and I think I have created a SMPTE-Stream, butt I'm not really sure....

For generating the Stream I'm using gstreamer 1.0 with the following command:

`gst-launch-1.0 rtpbin name=rtpbin videotestsrc horizontal-speed=2 !  video/x-raw,width=1280,height=720,framerate=24/1,format=UYVP ! rtpvrawpay pt=102 ! queue ! rtpbin.send_rtp_sink_0 rtpbin.send_rtp_src_0 ! queue ! udpsink host=239.0.0.0 port=5005 render-delay=0 rtpbin.send_rtcp_src_0 ! udpsink host=239.0.0.0 port=5005 sync=false async=false audiotestsrc ! audioresample ! audioconvert ! rtpL24pay ! application/x-rtp, pt=103, payload=103, clock-rate=48000, channels=2 ! rtpbin.send_rtp_sink_1 rtpbin.send_rtp_src_1 ! udpsink host=239.0.0.0 port=5007 render-delay=0 rtpbin.send_rtcp_src_1 ! udpsink host=239.0.0.0 port=5007 sync=false async=false` 

(the command I get from the Readme-File of FFmpeg)

Executing this command will generate this output (after 6 sek i press crtl+c):
`Setting pipeline to PAUSED ...`
`Pipeline is PREROLLING ...`
`Pipeline is PREROLLED ...`
`Setting pipeline to PLAYING ...`
`New clock: GstSystemClock`
`handling interrupt.`
`Interrupt: Stopping pipeline ...`
`Execution ended after 0:00:05.975982892`
`Setting pipeline to PAUSED ...`
`Setting pipeline to READY ...`
`Setting pipeline to NULL ...`
`Freeing pipeline ...`

I'm starting the capture with Wireshark before executing the command and ending it after the commandline tool returned.

After importing the PCAP-File into LIST, LIST will hang up allways at about 60%:
![Uploading](https://user-images.githubusercontent.com/38216271/44721769-48b98180-aacb-11e8-9329-f28011ecd542.PNG)

Reloading the side after about 1 minut the following will be shown:
![AfterUploading](https://user-images.githubusercontent.com/38216271/44721808-5f5fd880-aacb-11e8-808c-212624defa8a.PNG)
Configuring the Stream do not help, the analysis ends always in an error.

The PCAP-File you can find on https://share.ard-zdf-box.de/s/8zCmRJCybX49PBE (70.5MB)

PS: the SDP-File:
`# session`
`v=0`
`o=- 123456 11 IN IP4 239.0.0.0`
`s=A simple SMPTE ST 2110 session`
`i=basic streams for audio video`
`a=recvonly`

`# timing: unbounded and permanent session`
`t=0 0`

`# audio description first for better results`
`m=audio 5007 RTP/AVP 103`
`c=IN IP4 239.0.0.0/4`
`a=rtpmap:103 L24/48000/2`

`# video description`
`m=video 5005 RTP/AVP 102`
`c=IN IP4 239.0.0.0/4`
`a=rtpmap:102 raw/90000`
`a=fmtp:102 sampling=YCbCr-4:2:2; width=1280; height=720; depth=10; colorimetry=BT.709`

The command, to play this stream with ffmpeg (SDP-File is named 'test.sdp')
`ffplay test.sdp -protocol_whitelist file,udp,rtp -strict -2`

I hope you can help me : )

Thanks for your time

**Comment by promgamer** [comment]
Hi @dani-987 

Thank you for attaching the pcap file. I'll give you some feedback asap!

**Comment by dani-987** [comment]
Hey @promgamer ,

the PCAP-File is about 70MB big, so i cant upload it here... You can find here: https://share.ard-zdf-box.de/s/8zCmRJCybX49PBE

**Comment by promgamer** [comment]
@dani-987 

The problem with the file is that the framerate is `180000/7499
` (~24,003200427), instead of 24. I've manually configured the stream to 24Hz

![image](https://user-images.githubusercontent.com/6740813/44737472-fdfb3200-aae9-11e8-8e17-ab0f94043779.png)

And it worked for me:

![image](https://user-images.githubusercontent.com/6740813/44737495-0b182100-aaea-11e8-99a6-d199528ba67f.png)

Anyway, the stream is not compliant with ST2110-21.

**Comment by dani-987** [comment]
I have tried it before, it don't worked.... Now I've tried it again and its working, I don't know why... 

Thanks for your help :)
