### ISSUE TITLE
“Inter-frame RTP timestamps delta” non-compliance with a pass criteria wrongly set between min:1502 and max:1502

### ISSUE THREAD

**Issue by kmakesan** [ebu/pi-list#119]
Hello All,

For a 1080i2997 ST2110-40, an inter frame RTP delta between 1501 and 1502 would be ok.

EBU app reports a “Inter-frame RTP timestamps delta” non-compliance with a pass criteria set between min:1502 and max:1502.
The measured inter-frame RTP TS Delta by EBU LIST is: min:1501, avg:1501.5, max:1502.

would you please take a look ?

Regards.

**Comment by pedro-alves-ferreira** [comment]
Hello,

Can you please confirm which version of LIST you are using? I have just 
tried it with v1.17 and it seems to be working properly.

Thanks,

Pedro

**Comment by kmakesan** [comment]
Yes. V1.17.0 
See attached jpg file for the screenshot.
![EBU](https://user-images.githubusercontent.com/79132120/108123781-605a9b00-7074-11eb-987e-2a511e3e5122.JPG)

**Comment by pedro-alves-ferreira** [comment]
Thanks for confirming this. Would it be possible for you to send me a small pcap file that exhibits that problem? I have tested LIST with a few one from different sources and it seems to work fine for those.

Many thanks,

Pedro
________________________________
De: kmakesan <notifications@github.com>
Enviado: 16 de fevereiro de 2021 21:31
Para: ebu/pi-list <pi-list@noreply.github.com>
Cc: Pedro Ferreira <pedro@bisect.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [ebu/pi-list] “Inter-frame RTP timestamps delta” non-compliance with a pass criteria wrongly set between min:1502 and max:1502 (#119)


Yes. V1.17.0
See attached jpg file for the screenshot.
[EBU]<https://user-images.githubusercontent.com/79132120/108123781-605a9b00-7074-11eb-987e-2a511e3e5122.JPG>

**Comment by kmakesan** [comment]
[131-40_cc_Data_1.zip](https://github.com/ebu/pi-list/files/5997268/131-40_cc_Data_1.zip)
This is the pcap file inside the attached zip.

**Comment by pedro-alves-ferreira** [comment]
Thanks. I'll look at it asap.

Pedro
________________________________
De: kmakesan <notifications@github.com>
Enviado: 17 de fevereiro de 2021 16:59
Para: ebu/pi-list <pi-list@noreply.github.com>
Cc: Pedro Ferreira <pedro@bisect.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [ebu/pi-list] “Inter-frame RTP timestamps delta” non-compliance with a pass criteria wrongly set between min:1502 and max:1502 (#119)


131-40_cc_Data_1.zip<https://github.com/ebu/pi-list/files/5997268/131-40_cc_Data_1.zip>
This is the pcap file inside the attached zip.

**Comment by pedro-alves-ferreira** [comment]
Hello,

I think the problem derives from the fact that LIST is not detecting the 
right frame rate. This is apparent if you look in the Summary / Media 
information tab, where you can see that the field rate is calculated as 
45000/751 Hz.
The reason for this is the delta between the RTP Timestamps of 
successive packets. I am seeing an unusual and irregular sequence of 
deltas, namely 2, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, etc.

Are you sure the stream is compliant with ST2110-10, namely section 
7.5.1 [RTP Timestamps] General Provisions?

Regards,

Pedro

**Comment by kmakesan** [comment]
we have found the RTP clock root cause. 
Please close this issue.
Thanks for your help.
