### ISSUE TITLE
VM site in Network not available

### ISSUE THREAD

**Issue by philippdorn** [ebu/pi-list#12]
Hey Guys,

sorry for that but I have a new issue.

LIST ist running on a Ubuntu 18 in VMSphere.

I can reach LIST via localhost:8080 on the VM without any problems. But when I try to reach it via the network on my pc (in my case http://192.168.253.34:8080/) the site pops up for a micro second and dissapears right after that. The logo from EBU is shown in the tab from the browser, but the whole site is just white.
We also have other servers running on vm's and these server are reachable without any problems.

Any ideas?

Thanks for your help!

**Comment by promgamer** [comment]
Hi,

Can you check the browser's developer console? On Chrome and Firefox, you press F12 (and then select the "console" tab). There should be some error there, for sure. My bet is something related with CORS.

**Comment by philippdorn** [comment]
`Cross-Origin Request Blocked: The Same-Source Rule prohibits reading the external resource at http://192.168.253.34:3030/api/user. (Reason: CORS header 'Access-Control-Allow-Origin' does not match 'http: // localhost: 8080').
Cross-Origin Request Blocked: The same-source rule prohibits reading the external resource at http://192.168.253.34:3030/api/features. (Reason: CORS header 'Access-Control-Allow-Origin' does not match 'http: // localhost: 8080').
undefined
pageModifier.js:585:9
Mutation events should no longer be used. Use MutationObserver instead.
pageModifier.js:81:20
Unhandled promise rejection 
TypeError
​
columnNumber: 17874
​
fileName: "http://192.168.253.34:8080/list.ad2c1b.min.js"
​
lineNumber: 1
​
message: "this.state.error.config is undefined"
​
stack: "value@http://192.168.253.34:8080/list.ad2c1b.min.js:1:17874\n_n@http://192.168.253.34:8080/vendor.f1b593.min.js:1:81481\nNn@http://192.168.253.34:8080/vendor.f1b593.min.js:1:87057\nKn@http://192.168.253.34:8080/vendor.f1b593.min.js:1:95760\nQn@http://192.168.253.34:8080/vendor.f1b593.min.js:1:96068\nfr@http://192.168.253.34:8080/vendor.f1b593.min.js:1:99450\nlr@http://192.168.253.34:8080/vendor.f1b593.min.js:1:98959\nur@http://192.168.253.34:8080/vendor.f1b593.min.js:1:98785\nor@http://192.168.253.34:8080/vendor.f1b593.min.js:1:98157\nZn@http://192.168.253.34:8080/vendor.f1b593.min.js:1:97516\nenqueueSetState@http://192.168.253.34:8080/vendor.f1b593.min.js:1:129653\n[487]/o.prototype.setState@http://192.168.253.34:8080/vendor.f1b593.min.js:1:39255\nvalue/<@http://192.168.253.34:8080/list.ad2c1b.min.js:1:17415\nD/</<@http://192.168.253.34:8080/list.ad2c1b.min.js:1:247162\nD/<@http://192.168.253.34:8080/list.ad2c1b.min.js:1:247032\nl@http://192.168.253.34:8080/list.ad2c1b.min.js:1:77310\n"
​
__proto__: Object { stack: "", … }`

**Comment by promgamer** [comment]
Are you running a Docker version or a local one?

**Comment by philippdorn** [comment]
I installed it with docker.

**Comment by pkeroulas** [comment]
I got the same issue and had to replace `localhost` in `release/listwebserver/config.yml` with appropriate IP address. Not sure how handle that properly with the docker and docker-compose layer.

**Comment by promgamer** [comment]
Related with #14
