### ISSUE TITLE
Tvd

### ISSUE THREAD

**Issue by kierank** [ebu/pi-list#13]
Why do you just use the first packet arrival time instead of actually checking tvd relative to the epoch?

https://github.com/ebu/pi-list/blob/3dc5dbe251c26432521addb77156ee33c1466299/cpp/libs/st2110/lib/src/ebu/list/st2110/d21/vrx_calculator.cpp#L33

**Comment by kierank** [comment]
This is really confusing, how can something be VRX compliant with incorrect Tvd. We generated streams with known-bad Tvd and they came out green on the web analyser. 

It's simpler to pass VRX if you just define Tvd as the arrival time so I'm not sure why you do this. But yes we found no device yet which complies (probably setup related and lack of time to figure out why)

**Comment by pedro-alves-ferreira** [comment]
Hi Kieran,

You're right. We do the measurement using the 3 algorithms but are using the one which is the "easiest" to pass to label the streams. However, you if go and look at the graphs, you will see that the streams is not compliant.
We will fix this immediately and update the server as soon as possible.

**Comment by pedro-alves-ferreira** [comment]
I forgot to mention that we don't have access to the SDPs, so we don't know if the device advertises a TRoffset different than TROdefault. Using the fist packet of the first frame as the reference is a way of mitigating this.

**Comment by kierank** [comment]
I never really thought about a custom TRoffset to be honest, it doesn't seem to be explained well how you comply with the model at the same time as using a custom TRoffset.

**Comment by pedro-alves-ferreira** [comment]
That would be an interesting discussion. Are you at IBC? If yes and you can stop by the EBU booth, we could talk about that.

De: Kieran Kunhya <notifications@github.com>
Enviada: 13 September 2018 08:19
Para: ebu/pi-list <pi-list@noreply.github.com>
Cc: Pedro Ferreira <pedro@bisect.pt>; Comment <comment@noreply.github.com>
Assunto: Re: [ebu/pi-list] Tvd (#13)


I never really thought about a custom TRoffset to be honest, it doesn't seem to be explained well how you comply with the model at the same time as using a custom TRoffset.

**Comment by kierank** [comment]
Yes but I am at our booth 7.a49

**Comment by pedro-alves-ferreira** [comment]
Updated in latest version.
