### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by garethsb** [ebu/pi-list#143]
The spelling "sucess" rather than "success" appears in the API doc and implementation:
E.g.
https://github.com/ebu/pi-list/blob/d8b0028404d103e1f3e55fc614ea99397768e683/docs/api.md?plain=1#L128

**Comment by pedro-alves-ferreira** [comment]
Thanks, @garethsb! We'll correct that.

**Comment by pedro-alves-ferreira** [comment]
Fixed in v2.0.5
