### ISSUE TITLE
charset

### ISSUE THREAD

**Issue by garethsb** [ebu/pi-list#144]
Should `charset` be used on the `application/json` content type?

https://github.com/ebu/pi-list/blob/d8b0028404d103e1f3e55fc614ea99397768e683/docs/api.md?plain=1#L14

Although implementations may accept/provide the charset, the [IANA media type registration](https://www.iana.org/assignments/media-types/application/json) explains why `charset` is NOT defined for `application/json`.

**Comment by pedro-alves-ferreira** [comment]
Thanks, @garethsb! We'll correct that.

**Comment by pedro-alves-ferreira** [comment]
Fixed in v2.0.5
