### ISSUE TITLE
LIST Online - registration and login fails

### ISSUE THREAD

**Issue by schoettlerf** [ebu/pi-list#153]
Hello everybody,

I am not sure if this is the right place for reporting issues with the website :)
It seems that the public LIST server is currently not available? 

Both, the login and the registration process are not successfull.
- Error message login: "The credentials used are not correct"
- Error message registration: "The username is already being used"

![image](https://user-images.githubusercontent.com/92024101/214045583-aeff1c83-0cdc-42d3-a74d-304f14280735.png)

The browser console shows a HTTP-502 Status at page load?

Best Regards
Fabian

**Comment by pedro-alves-ferreira** [comment]
Hello Fabian,

Thanks for reporting this. The server ran out of space. It should be fine now.

Best rgards,

Pedro

**Comment by schoettlerf** [comment]
Hey Pedro,

thank you very much for resolving the issue that fast!

I just want to add that I really enjoy working with LISTv2. Great tool!!

Best Regards
Fabian

**Comment by pedro-alves-ferreira** [comment]
No problem! It's great to know that. Many thanks!
