### ISSUE TITLE
Selection of gapped or linear read schedule for analysis

### ISSUE THREAD

**Issue by David-P-B** [ebu/pi-list#17]
I uploaded a 1080p25 uncompresssed video stream with traffic shaping from a wide sender, which should be analysed using a linear read schedule (as per SMPTE 2110-21 wide sender).

The LIST software analysed the stream using a gapped read schedule. 
There is no mechanism to specifiy the sender type or required read schedule.

**Comment by pedro-alves-ferreira** [comment]
Hi David,

Thanks for opening the issue.

Regards,

Pedro


No dia 03/10/2018, às 09:12, David Butler <notifications@github.com<mailto:notifications@github.com>> escreveu:


I uploaded a 1080p25 uncompresssed video stream with traffic shaping from a wide sender, which should be analysed using a linear read schedule (as per SMPTE 2110-21 wide sender).

The LIST software analysed the stream using a gapped read schedule.
There is no mechanism to specifiy the sender type or required read schedule.

**Comment by pedro-alves-ferreira** [comment]
Linear or gapped schedules are now detected automatically by the pre-analysis heuristics. @David-P-B: Do you think this is good enough?
