### ISSUE TITLE
Cfull / VRX analysis over full capture data

### ISSUE THREAD

**Issue by David-P-B** [ebu/pi-list#18]
The LIST software seems to measure maximum Cfull & VRX buffer sizes on a per frame basis.
My understanding is that, especially for a wide sender, the values should be measured over all captured data. Buffer offsets from previous frames can have a cumulative affect, resulting in much larger maximum Cfull and VRX values. 
The results I've seen so far (from software senders) also increase with capture duration. It may be worth recommending a mimimum capture size (in packets or time) for tests.

**Comment by pedro-alves-ferreira** [comment]
Hi David,

Can you please provide a small pcap file where we can see this problem?

Thanks
