### ISSUE TITLE
Block Packing Mode exhibit weird packet sequence

### ISSUE THREAD

**Issue by felixpou** [ebu/pi-list#21]
When analyzing a capture of a sender using Block Packing Mode, the packet numbering doesn't seems right for the first packets in the video frame (and so are all the calculations good?) - I sent the pcap to the developpers.

![image](https://user-images.githubusercontent.com/4963200/46923539-2e8a2300-cfe7-11e8-925d-12df4363b261.png)

**Comment by pedro-alves-ferreira** [comment]
Thanks, Felix. I'll see if this is related to #22.

**Comment by pedro-alves-ferreira** [comment]
Hi Félix. I found the problem. It was actually just a rendering problem. Everything else is fine. I will merge the PR soon.
