### ISSUE TITLE
UHD analysis hang-out

### ISSUE THREAD

**Issue by felixpou** [ebu/pi-list#22]
I uploaded a capture of UHD content, probably Block Packing Mode with last packet padded. 

Information tab says "Packets per Frame 16458" which makes sense. 
But in the stream explorer, it **only shows 1 to 554 packets for each frame**, the 554th being the one with the marker bit.
Cinst and VRX calculation seems to make sense even so.

I sent the capture to the developers.

**Comment by pedro-alves-ferreira** [comment]
Thanks, Felix. I'll look into it asap.
