### ISSUE TITLE
Version number in GUI and calculation info

### ISSUE THREAD

**Issue by David-P-B** [ebu/pi-list#23]
Given that there are / have been changes in the VRX calcualtion, in would be very useful to see a version number in the LIST GUI, with a link to a description of the CFull and VRX calculation assumptions + a version history.

**Comment by pedro-alves-ferreira** [comment]
Thanks, David. We're working on that.

**Comment by pedro-alves-ferreira** [comment]
The version number and git commit hash are now presented in the GUI.
We have a file that describes the C and Vrx algorithms in the docs folder, reachable from README.md.
