### ISSUE TITLE
Demo page doesn't do anything

### ISSUE THREAD

**Issue by kierank** [ebu/pi-list#3]
I uploaded a file, set the parameters but nothing happens on the demo web page.

**Comment by pedro-alves-ferreira** [comment]
Hi Kieran,

Can you please email or otherwise make available the file you uploaded?

Many thanks,

Pedro

No dia 14/07/2018, às 13:28, Kieran Kunhya <notifications@github.com<mailto:notifications@github.com>> escreveu:


I uploaded a file, set the parameters but nothing happens on the demo web page.

**Comment by kierank** [comment]
Sure is, there an email address I should send to?

**Comment by pedro-alves-ferreira** [comment]
Sure. Please send it to myself (pedro@bisect.pt<mailto:pedro@bisect.pt>) and to Miguel Poeira (miguel@bisect.pt<mailto:miguel@bisect.pt>).

Thanks,

Pedro

No dia 15/07/2018, às 02:20, Kieran Kunhya <notifications@github.com<mailto:notifications@github.com>> escreveu:


Sure is, there an email address I should send to?

**Comment by kierank** [comment]
I can't login to http://51.136.33.162/login any more so I have no idea whether it works or not.

**Comment by promgamer** [comment]
@kierank I'm sorry for the unavailability. We run out of disk space. It's solved! Please try again.

**Comment by kierank** [comment]
The file opens at least, not sure if VRX is meant to be like this, the sender (Ross Newt) is very buggy to begin with.

**Comment by promgamer** [comment]
@kierank what do you mean "like this"? Can you share your results?

**Comment by promgamer** [comment]
@kierank we've just rolled out a new update to our dematerialized version, which fixes a lot of GUI bugs. Care to try again?
