### ISSUE TITLE
deploy.sh line 40

### ISSUE THREAD

**Issue by dewiweb** [ebu/pi-list#37]
'''
cp -R $TOP_DIR/apps/gui/dist/* $RELEASE_DIR/server/app/gui
'''
but no dist folder in repo

**Comment by pedro-alves-ferreira** [comment]
Don't you see the "Compiling GUI" message? The dist dir is created by build.sh:
```
echo "Compiling GUI..."
cd $TOP_DIR/apps/gui/
npm install && npm run production
echo "Compiling GUI... done"
```

**Comment by dewiweb** [comment]
apparently not in my first sdev environment but I ran another deploy on a second computer and it deploys well.
I'll investigate tomorrow to find more info...

**Comment by pedro-alves-ferreira** [comment]
Ok. Let us know.

**Comment by dewiweb** [comment]
Ok succesfully deploy on my first dev environment, apprently this issue is due to wheel module not installed in python3. After a ''' pip install whell ''' all is going right.

**Comment by pedro-alves-ferreira** [comment]
Great. Thanks for letting us know.
