### ISSUE TITLE
Better axis labeling

### ISSUE THREAD

**Issue by fschoett** [ebu/pi-list#39]
Hello!

I am currently working with the LIST tool to analyze ST2110-20 HD video stream captures.

One thing I have trouble with is to understand the different graphs, because the labels of the X-axis of those graphs (for example Vrx, Tvd and RTP graphs) are not very intuitive in my opinion. 

![Screenshot VRX graphs](https://user-images.githubusercontent.com/40275398/57220679-8bd5d800-6ffc-11e9-8170-edbea68af93b.JPG)

I think that displaying the units of the X-axis would be very helpful! Also the ability to show time stamps, relative packet number and or sequence number would be a nice feature!

Best Regards

-Fabian

**Comment by pedro-alves-ferreira** [comment]
Hello Fabian,

Many thanks for your feedback. This is something we are aware of but we haven't yet had time to address. We will try to push this up on our backlog.

Best regards,

Pedro
