### ISSUE TITLE
Analysis failure of an audio capture

### ISSUE THREAD

**Issue by gregshay79** [ebu/pi-list#44]
Great tool!
Seeing an analysis failure with a simple audio only file.
On the console of the host running the docker container seeing this error message:
" list_server_1  | 2019-06-28T15:51:31.836Z [stream-reset-counters] error: exception: TypeError: Cannot set property 'packet_count' of undefined "

Thought you might like the sample of the failing capture file (attached).
Thanks,
Greg

[capture24899.zip](https://github.com/ebu/pi-list/files/3339988/capture24899.zip)

Note: When this capture file is loaded, no automatic format is recognized.   When using the configuration interface, I try to put in L24, 48Khz, 2 channels, 1ms.   Then the error message comes up on the console.

**Comment by pedro-alves-ferreira** [comment]
Hello Greg,

Thanks for trying LIST OUT and for the feedback. We'll look into it asap.

Regards,

Pedro

No dia 28/06/2019, às 17:04, gregshay79 <notifications@github.com<mailto:notifications@github.com>> escreveu:


Great tool!
Seeing an analysis failure with a simple audio only file.
On the console of the host running the docker container seeing this error message:
" list_server_1 | 2019-06-28T15:51:31.836Z [stream-reset-counters] error: exception: TypeError: Cannot set property 'packet_count' of undefined "

Thought you might like the sample of the failing capture file (attached).
Thanks,
Greg

capture24899.zip<https://github.com/ebu/pi-list/files/3339988/capture24899.zip>

**Comment by pkeroulas** [comment]
Hello Greg,
I'll address that this week. Sorry for the delay.
Thanks,
PK

**Comment by gregshay79** [comment]
Ok, looking forward to it
Greg

**Comment by gregshay79** [comment]
Reflecting on the behavior, it may not be the file itself.  It seems to be
related to manually entering the format.
Greg

**Comment by pedro-alves-ferreira** [comment]
Hello Greg,

Patrick has solved in the re-analysis issue and it is integrated in latest version in github, in the docker registry and in list.ebu.io.
I still haven't checked why it is not detecting the format correctly. I suspect it may be because of the 2 dropped packets but I will check that a.s.a.p.

Regards,

Pedro

**Comment by gregshay79** [comment]
Thank you for your work!  This tool is becoming more important to our work.
Best regards
Greg Shay
CTO
The Telos Alliance
