### ISSUE TITLE
docker-compose up does not work

### ISSUE THREAD

**Issue by JeanMTX** [ebu/pi-list#48]
following A short guide to install and run EBU-LIST...
installed docker desktop for windows 10.
enabled HyperV (which maybe you should mention)
Running Docker desktop...

Follow all the step successfully until docker-compose up.

I get:
PS C:\dockerEBU> docker login -u jeanlapierre
Password:
Login Succeeded
PS C:\dockerEBU> docker-compose up
WARNING: The EBU_LIST_WEB_APP_DOMAIN variable is not set. Defaulting to a blank string.
WARNING: The EBU_LIST_LIVE_MODE variable is not set. Defaulting to a blank string.
ERROR: build path C:\dockerEBU\server either does not exist, is not accessible, or is not a valid URL.
PS C:\dockerEBU>

**Comment by pedro-alves-ferreira** [comment]
Hello Jean,

Can you please post your C:\dockerEBU\docker-compose.yml file here? 
I find the error message odd because nothing should be built. Docker should just pull the already built container from docker hub.

Thanks,

Pedro


No dia 24/07/2019, às 00:44, JeanMTX <notifications@github.com> escreveu:

> C:\dockerEBU

**Comment by JeanMTX** [comment]
Hi,

Based on your comment I went ahead and got the docker-compose.yml again from
https://raw.githubusercontent.com/ebu/pi-list/master/docs/docker-compose.yml
I pasted it over what I had, it looked the same but this time it worked.
There must have been control characters inserted last time when I copy pasted from the webpage directly.

Sorry for that.
You can close the issue.

**Comment by pedro-alves-ferreira** [comment]
Hi Jean,

No problem! I'm glad it is now working.

Thanks,

Pedro
