### ISSUE TITLE
What does Vrx -1 mean?

### ISSUE THREAD

**Issue by YaoDing** [ebu/pi-list#53]
Hi there,
This is really just a question rather than an issue.
During my testing, sometimes I saw it failed on VRX saying "VRX is above VRXFULL"
But from the Analysis, it showed the max value is 4 which did not hit VRXFULL(8).
<img width="1318" alt="Screen Shot 2019-09-06 at 2 30 44 PM" src="https://user-images.githubusercontent.com/12861012/64455123-cdfe4b80-d0ba-11e9-8abe-5011dd677fa6.png">
And the minimum value is -1, how do we calculate it and what does it mean?
Thanks,

**Comment by pedro-alves-ferreira** [comment]
Hi!

Indeed, the message is misleading. I will change it to "VRX is outside the valid bounds". Many thanks for your feedback.

VRX with negative values means that the virtual receiver tried to read a packet when there was none in the virtual buffer.
In other words, it means that one or more packets were sent slightly later than they should.

I hope this helps.

Regards

**Comment by YaoDing** [comment]
> Hi!
> 
> Indeed, the message is misleading. I will change it to "VRX is outside the valid bounds". Many thanks for your feedback.
> 
> VRX with negative values means that the virtual receiver tried to read a packet when there was none in the virtual buffer.
> In other words, it means that one or more packets were sent slightly later than they should.
> 
> I hope this helps.
> 
> Regards

Thanks@Pedro, it helps.
