### ISSUE TITLE
Instruction tweak

### ISSUE THREAD

**Issue by FOXNEOAdvancedTechnology** [ebu/pi-list#6]
Where the instructions say "run ./start.sh", I find it needs to be "sudo run ./start.sh".

**Comment by promgamer** [comment]
What the `./start.sh` script does, in fact, is a `docker-compose up --build -d`, so if you need to add `sudo` to it, my best guess is that, when you installed docker, you forgot to create the `docker` group and add users to it, as it is described [here](https://docs.docker.com/install/linux/linux-postinstall/).

**Comment by FOXNEOAdvancedTechnology** [comment]
Aha, that solves the problem, thanks! (I also had to reboot to make the add of my user to docker group work)
