### ISSUE TITLE
Trouble with Docker

### ISSUE THREAD

**Issue by FOXNEOAdvancedTechnology** [ebu/pi-list#7]
I am getting this after running ./start.sh:

Step 12/14 : COPY gui/ /app/gui/
ERROR: Service 'list_server' failed to build: lstat gui/: no such file or directory

Running on AWS Ubuntu Server 16.04 LTS

Any chance you have an AMI or VM image of a working system?

**Comment by promgamer** [comment]
It does mean that the "gui" folder was not there (on `release` folder). Can you check if you have the gui folder inside the `release` folder? That's from where all the commands (start, pause, stop) should be invoked.

I would like to have a public docker image of LIST, which would make private deploys much easier.

**Comment by FOXNEOAdvancedTechnology** [comment]
There is no "gui" folder in my "pi-list/release" folder.  (Running ./start as a non-root user, moved up to Ubuntu 18.04 on VirtualBox locally).

**Comment by promgamer** [comment]
@sundayN about the `sudo`part, please check #6 please. About the application being stuck, you can access the logs by doing `docker-compose logs | grep list_`.

@FOXNEOAdvancedTechnology there was some kind of error while deploying. Can you run the `deploy.sh` script again and pay attention to the logs it outputs? I'm sure there will be an error there (we should enhance that script to better detect errors and stop the deploy).

**Comment by sundayN** [comment]
@promgamer Thanks - I added the docker post install instructions.  Here are the errors from the logs  list_server_1  | 2018-08-02T14:14:16.531Z [server] info: LIST Web Server listening on 3030 
list_server_1  | 2018-08-02T14:14:16.536Z [static-generator] error: /bin/sh: 1: /app/bin//static_generator: not found

**Comment by sundayN** [comment]
@promgamer you are indeed correct, it is not correctly compiled. the deploy script has some errors, which I will look into. 

Copying binaries...
cp: cannot stat 'build/bin/stream_pre_processor': No such file or directory

I agree with your statement earlier that it should not "deploy" if errors exist

**Comment by promgamer** [comment]
@sundayN we definitely should improve the deploy script in order to prevent from deploying if errors exist :+1:

**Comment by promgamer** [comment]
@FOXNEOAdvancedTechnology I've just uploaded a public docker image on https://hub.docker.com/r/ebutech/pi-list/tags/, which is ready for use.

You need to replace the build step on docker-compose.yml by the image from docker hub. I need to update Github's readme with that info.

Let me know if that works for you.

**Comment by promgamer** [comment]
Current version @ master already includes how to use the docker hub's image. Closing this issue.
