### ISSUE TITLE
PDF report is blanc

### ISSUE THREAD

**Issue by kuipers-axon** [ebu/pi-list#74]
Hi, we are using the Dockerized version of ebu-list. After uploading some pcap files we want to download a PDF report. A single page PDF is generated but the page is blanc.

If I check the logs I got the following messages which could be a point of interest.

```
list_server_1  | info: TypeError: null is not an object (evaluating 'document.getElementById('file-name').innerHTML =
list_server_1  | info:                             report.file_name')
list_server_1  | info:   undefined:3 in anonymous
list_server_1  | info:   :115
list_server_1  | 2020-01-14T10:31:02.997Z [rest-api] info: ::ffff:127.0.0.1 - GET /api/pcap/f5468c80-1dbc-11ea-b757-75b5ab8199f5/report?type=pdf HTTP/1.0 200 1210 - 388.954 ms
```
Does the dowload of a PDF report work for other users?

I found the code which is associated with the TypeError but I don't know how to solve this issue by the lack of NodeJS knowledge. 

Best regads,
Mark

**Comment by dangerware** [comment]
Hi Mark, thank you for taking the time!
We've reproduced the same problem you've described and will get back once we've fixed it.

**Comment by dangerware** [comment]
Hello again, Mark. The problem was fixed. The code should be merged to this repository in the next few days. Once again, thank you for taking the time.

**Comment by kuipers-axon** [comment]
Hi dangerware, thank you for fixing the problem so fast! I will update the container when a new docker image comes available. Thanks you for the fast response.

Grtz,
Mark

**Comment by dangerware** [comment]
Hi Mark, a new Docker image is available which contains the fix for this problem. The changes should also be merged to this repository today. Could you please test it and close this issue if it is working as intended?

Have a nice weekend!

**Comment by kuipers-axon** [comment]
Hi, Just updated the docker container to the latest version and now the PDF functionality is working again. Thanks for the quick fix!

I will close this issue
