### ISSUE TITLE
"dematerialized" version is not avaible, server do not aswers

### ISSUE THREAD

**Issue by dani-987** [ebu/pi-list#8]
I'm using Google Chrome and since yesterday http://51.136.33.162/ do not aswers. 
Chrome's Errormessage is "ERR_CONNECTION_TIMED_OUT"

Screenshot:
![dematerialized_not_avaible](https://user-images.githubusercontent.com/38216271/43820889-d04ae196-9ae7-11e8-9953-76e9300d3467.PNG)

PS: last time i opened it (2 weeks ago), it was working fine....

Thank you for checking it :)

**Comment by promgamer** [comment]
Hi @dani-987 

We are having some trouble with the *dematerialized* version. It will be online in a couple of hours from now.

Cheers,
Miguel

**Comment by promgamer** [comment]
**Update**: 
LIST is live again @ http://13.81.30.174. You'll need to create a new account. I'm sorry for that. Right now, it's not planned to recover the information that we had in the other server. Let me know if this can be a problem for you.

Even though it's not updated yet, please use http://list.ebu.io/ to access LIST, as it abstracts the underlying IP address.

**Comment by dani-987** [comment]
Thank you for bringing LIST live again @promgamer . It isn't a problem, that the information isn't recovered :)

fyi: the link to the dematerialized version on https://tech.ebu.ch/list is still linking the old IP (51.xxx) and http://list.ebu.io/ do not answer. I can only access that version by using the IP-address you have mentioned (13.xxx)...
