### ISSUE TITLE
Couldn't upload large sized captures

### ISSUE THREAD

**Issue by Ahmad-Qarmash** [ebu/pi-list#84]
Hi,

I'm trying to upload pcap captured from a 4k 25fps video which sized 1.2GB

Using the site: `https://list.ebu.io/pcaps` pcap file didn't upload at all, is there a size limit ?

Using our own instance of LIST i'm getting a non-configurable stream.

Tried to reduce the size of the capture to 300MB, it worked fine and analyzed with no issues. 

Is there a way we can get the large sized captures to work ?

**Comment by pedro-alves-ferreira** [comment]
Hello,

There is no hard limit but the upload may be cancelled if the storage is reaching the limit.
If you want to analyze large files, please install LIST locally, as explained in:

https://github.com/ebu/pi-list/blob/master/docs/local_docker.md

Thanks,

Pedro Ferreira

**Comment by Ahmad-Qarmash** [comment]
Hi Pedro,

I have tried to install LIST locally and I'm getting the following error:
`listserver_1        | 2020-06-10T10:57:53.980Z [mq] error: Error connecting to AMQP broker: Error: connect ECONNREFUSED 172.19.0.3:5672
influxdb_1          | [I] 2020-06-10T10:57:50Z Listening for signals
influxdb_1          | [I] 2020-06-10T10:57:50Z Sending usage statistics to usage.influxdata.com
listserver_1        | 2020-06-10T10:57:54.977Z [mq] info: Health checker: trying to create receiver
listserver_1        | 2020-06-10T10:57:54.978Z [mq] info: [AMQP] connecting to amqp://rabbitmq:5672
listserver_1        | 2020-06-10T10:57:54.979Z [mq] error: Error connecting to AMQP broker: Error: connect ECONNREFUSED 172.19.0.3:5672
ebu-pi-list_listreverseproxy_1 exited with code 1`

**Comment by kalstong** [comment]
Hi Ahmad,

I'm assuming that you have followed this step of the documentation: https://github.com/ebu/pi-list/blob/master/docs/local_docker.md#how-to-run-your-instance-of-list

I'll ask you to to the following, instead of `docker-compose up` do `docker-compose up --build --force-recreate`

Your setup is windows or Linux based?

**Comment by kalstong** [comment]
Can you also do `docker image ls --digests` and compare the **_ebutech/pi-list_** with this one:
`ebutech/pi-list                             latest              sha256:f79a33e17bc0f2e7af3e74d4bb5ae050185b25248d5055
       │ d529dd0246eb29a08a   7ca658eeae6a        6 days ago          2.49GB`

**Comment by Ahmad-Qarmash** [comment]
Hi Ricardo,

Thanks a lot, this line solves it: `docker-compose up --build --force-recreate`

my setup is Linux based (Ubuntu 18.04)

my docker image ls --digests shows the following:
`ebutech/pi-list                             latest            sha256:f79a33e17bc0f2e7af3e74d4bb5ae050185b25248d5055d529dd0246eb29a08a   7ca658eeae6a        6 days ago          2.49GB`

**Comment by kalstong** [comment]
Ok, if you find problems accessing `http://localhost` please do `http://localhost/?t=1234` to force browser to not use cache for this particular URL.

**Comment by Ahmad-Qarmash** [comment]
Yes, I can access using` http://localhost` but https showing privacy issue.

**Comment by kalstong** [comment]
Yes, HTTPS only works if you define a environment variable.
If you prefer HTTPS, you can `EBU_LIST_WEB_APP_DOMAIN="https://localhost:443" docker-compose up --build --force-recreate`
After that you can access via `https://localhost`

**Comment by kalstong** [comment]
Ahmad, the certificate is self signed, you will see an alert in the browser.

**Comment by kalstong** [comment]
Ahmad,

Feel free to close the issue, if you got the solution for the issue.

Regards,
Ricardo

**Comment by Ahmad-Qarmash** [comment]
Sure, I'm trying to upload two video pcap captures [1080 interlace 60fps]to the EBU, one of them is analyzed and shows it is a spec compliant while the other is showing this,
![image](https://user-images.githubusercontent.com/42785013/84568157-36830300-ad86-11ea-8717-0a196e5b7dd5.png)

After pressing on it shows nothing and if i click download PDF it shows the following:
![image](https://user-images.githubusercontent.com/42785013/84568274-da6cae80-ad86-11ea-8ca5-46051d9993ea.png)

Attached the two pcap files,
[configurable_pcap.zip](https://github.com/ebu/pi-list/files/4774546/configurable_pcap.zip)
[non-configurable_pcap.zip](https://github.com/ebu/pi-list/files/4774549/non-configurable_pcap.zip)

**Comment by pedro-alves-ferreira** [comment]
Hello Ahmad,

I'll try to check the files later today.

Regards,

Pedro

**Comment by pedro-alves-ferreira** [comment]
Hello Ahmad,

According to Wireshark, the packets are malformed. See the image below.
This is why LIST does not identify any stream.

Regards,

Pedro

**Comment by Ahmad-Qarmash** [comment]
Hi Pedro,

The image does not appear. but i will recheck.

**Comment by pedro-alves-ferreira** [comment]
Sorry. I guess GitHub doesn't embed images when I reply to the email. Here it is.
![image](https://user-images.githubusercontent.com/20090304/84770433-74bf3300-afcf-11ea-810d-04f351b0dbe4.png)

**Comment by Ahmad-Qarmash** [comment]
Thanks a lot Pedro / Ricardo for your help,

Wireshark was not showing those errors to show them i need to go to: analyze -> Enabled protocols -> and check the rtps_udp. then it will show those RTP errors.

Thanks,
Ahmad

**Comment by pedro-alves-ferreira** [comment]
You're welcome! Thanks for closing the issue.

Regards,

Pedro
