### ISSUE TITLE
Cannot analyse RTP-Stream created with VLC-Player and Wireshark

### ISSUE THREAD

**Issue by dani-987** [ebu/pi-list#9]
When I'm starting analysing a stream with the online version of LIST, I get only "Unknown" streams:

<img width="551" alt="listafteranalysis" src="https://user-images.githubusercontent.com/38216271/43896020-a2743bfa-9bd7-11e8-840d-06143cca2a61.PNG">
<img width="580" alt="listdetail" src="https://user-images.githubusercontent.com/38216271/43896028-a6e79a74-9bd7-11e8-91b3-ae9eb5634d53.PNG">

The created stream is based on the stream you can get at https://archive.org/download/BigBuckBunny_124/Content/big_buck_bunny_720p_surround.mp4 . The RTP-stream was created in the following steps:
1.  strg+s
2.  add video + click on "stream"
3.  "next"
4.  select "RTP/MPEG Transport Stream" + click on "Add"
5.  IP: "224.2.2.4" Port: "5004" + click on "next"
6.  select "Video - H.264 + MP3 (MP4)" + click on "next" (transcoding activated)
7.  "stream"

The stream was recoded on the client side. The pcap-file you can donwload here: https://share.ard-zdf-box.de/s/QaS3x7aCyiCK3k3

Am I doing something wrong? Can you help me please, how to get the stream analyzed? Thank you for your help :)

**Comment by promgamer** [comment]
@dani-987 Can you give details that would be on a SDP file (chroma sub-sampling, color depth, framerate, scan mode, etc)?

**Comment by dani-987** [comment]
@promgamer:
Here is a screenshot of the codec-information given by VLC-Player (sry, its german...):
![unbenannt](https://user-images.githubusercontent.com/38216271/43901852-cc844a96-9be8-11e8-8416-8695304ce665.PNG)

According to this screenshot the values should be:
chroma sub-sampling is i think 4:2:0 YUV
frame rate: 24 fps

If you can tell me how to get the other information I can tell you them too....

**Comment by promgamer** [comment]
@dani-987 right now, we only support YUV 4:2:2

Anyway, I've downloaded your PCAP and it seems that you're sending a MPEG-TS stream, which is not a ST2110-compliant. If you want a tool to simulate 2110 traffic, maybe take a look at [this](https://github.com/cbcrc/FFmpeg).

**Comment by dani-987** [comment]
thank you for your answer :) I will try this tool and answer you later, if it works or not....

**Comment by dani-987** [comment]
I have tried to generate an smpte stream with ffmpeg but until now I wasn't successful (never worked with ffmpeg before). In the next time I won't have time for tring it again, so I'll try it in about 2 weeks again....
I hope it's ok for you

**Comment by promgamer** [comment]
Sure it's ok! I'll close the issue right now. Try it again when you do have time and open an issue if you need some help.
