### ISSUE TITLE
Live Stream mode

### ISSUE THREAD

**Issue by kuipers-axon** [ebu/pi-list#99]
Hi,

We would like to try the Live Stream mode for analysis. Is there already some documentation on how to use this feature?

Thanks in advance!

Grtz,
Mark Kuipers

**Comment by pedro-alves-ferreira** [comment]
Hi Mark,

Unfortunately, this feature was put on hold a long time ago and there are no plans to keep on developing it.

Regards,

Pedro

**Comment by kuipers-axon** [comment]
Hi Pedro,

Thanks for your reply. Then we skip this feature for now.

I will close this issue.

Regards,
Mark
